<?php
/**
 * Title: Statistics Section
 * Slug: squirrels/marketing-statistics
 * Categories: squirrels-marketing
 * Keywords: statistics, numbers, metrics, social proof, data, achievements, count
 * Description: Full marketing statistics section with a heading, sub-text, and four large stat blocks in a horizontal row. Use on landing pages to establish credibility with numbers.
 */
?>

<!-- wp:group {"className":"squirrels-statistics-section","align":"full","style":{"spacing":{"padding":{"top":"var:preset|spacing|70","bottom":"var:preset|spacing|70"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull squirrels-statistics-section">

	<!-- wp:group {"layout":{"type":"constrained","contentSize":"560px"},"style":{"spacing":{"margin":{"bottom":"var:preset|spacing|60"}}}} -->
	<div class="wp-block-group">
		<!-- wp:heading {"textAlign":"center","level":2} -->
		<h2 class="has-text-align-center">Trusted by store owners worldwide</h2>
		<!-- /wp:heading -->
		<!-- wp:paragraph {"align":"center"} -->
		<p class="has-text-align-center">These numbers reflect the stores, customers, and revenue generated by merchants using Squirrels every day.</p>
		<!-- /wp:paragraph -->
	</div>
	<!-- /wp:group -->

	<!-- wp:columns {"className":"squirrels-stats-row__grid squirrels-statistics-section__grid"} -->
	<div class="wp-block-columns squirrels-stats-row__grid squirrels-statistics-section__grid">

		<!-- wp:column {"className":"squirrels-stat"} -->
		<div class="wp-block-column squirrels-stat">
			<!-- wp:heading {"textAlign":"center","level":3,"className":"squirrels-stat__number"} -->
			<h3 class="has-text-align-center squirrels-stat__number">12,000+</h3>
			<!-- /wp:heading -->
			<!-- wp:paragraph {"align":"center","className":"squirrels-stat__label"} -->
			<p class="has-text-align-center squirrels-stat__label">Active stores</p>
			<!-- /wp:paragraph -->
		</div>
		<!-- /wp:column -->

		<!-- wp:column {"className":"squirrels-stat"} -->
		<div class="wp-block-column squirrels-stat">
			<!-- wp:heading {"textAlign":"center","level":3,"className":"squirrels-stat__number"} -->
			<h3 class="has-text-align-center squirrels-stat__number">$48M</h3>
			<!-- /wp:heading -->
			<!-- wp:paragraph {"align":"center","className":"squirrels-stat__label"} -->
			<p class="has-text-align-center squirrels-stat__label">Revenue processed</p>
			<!-- /wp:paragraph -->
		</div>
		<!-- /wp:column -->

		<!-- wp:column {"className":"squirrels-stat"} -->
		<div class="wp-block-column squirrels-stat">
			<!-- wp:heading {"textAlign":"center","level":3,"className":"squirrels-stat__number"} -->
			<h3 class="has-text-align-center squirrels-stat__number">4.9 / 5</h3>
			<!-- /wp:heading -->
			<!-- wp:paragraph {"align":"center","className":"squirrels-stat__label"} -->
			<p class="has-text-align-center squirrels-stat__label">Average rating</p>
			<!-- /wp:paragraph -->
		</div>
		<!-- /wp:column -->

		<!-- wp:column {"className":"squirrels-stat"} -->
		<div class="wp-block-column squirrels-stat">
			<!-- wp:heading {"textAlign":"center","level":3,"className":"squirrels-stat__number"} -->
			<h3 class="has-text-align-center squirrels-stat__number">99.9%</h3>
			<!-- /wp:heading -->
			<!-- wp:paragraph {"align":"center","className":"squirrels-stat__label"} -->
			<p class="has-text-align-center squirrels-stat__label">Uptime guaranteed</p>
			<!-- /wp:paragraph -->
		</div>
		<!-- /wp:column -->

	</div>
	<!-- /wp:columns -->

</div>
<!-- /wp:group -->
